# Generated by Django 6.0.6 on 2026-07-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhumation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_defunt', models.CharField(max_length=255)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REFUSEE', 'Refusée'), ('EFFECTUEE', 'Effectuée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_exhumation', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
            ],
        ),
    ]
