# Generated by Django 6.0.6 on 2026-07-10 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caveaux', '0001_initial'),
        ('exhumations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exhumation',
            name='approuve_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhumations_approuvees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='caveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to='caveaux.caveau'),
        ),
        migrations.AddField(
            model_name='exhumation',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhumations', to=settings.AUTH_USER_MODEL),
        ),
    ]
