# Generated by Django 6.0.6 on 2026-07-10 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caveaux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_concession', models.CharField(choices=[('TEMPORAIRE', 'Temporaire'), ('PERPETUELLE', 'Perpétuelle')], max_length=20)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIREE', 'Expirée'), ('RESILIEE', 'Résiliée')], default='ACTIVE', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concessions', to='caveaux.caveau')),
            ],
        ),
    ]
