[providers]
python = {}

[phases.setup]
# Force l'installation des paquets de géolocalisation requis pour PostGIS sous Linux
aptPkgs = ["gdal-bin", "libgdal-dev", "binutils", "libproj-dev", "g++"]

[start]
cmd = "gunicorn cimetiere.wsgi:application --bind 0.0.0.0:$PORT"